### ISSUE TITLE
iOS14 崩溃

### ISSUE THREAD

**Issue by storm890612** [Allen0828/AEAlertView#2]
func showAlert() {
...
        if #available(iOS 13, *) {
            UIApplication.shared.keyWindow?.addSubview(self)
        } else {
            UIApplication.shared.delegate?.window??.addSubview(self)
        }
...
}
UIApplication.shared.keyWindow 在iOS13以后被废弃

**Comment by Allen0828** [comment]
use:
if #available(iOS 14.0, *) {
            let window = UIApplication.shared.windows.first { $0.isKeyWindow }
            window?.addSubview(self)
        } else if #available(iOS 13, *) {
            UIApplication.shared.keyWindow?.addSubview(self)
        } else {
            UIApplication.shared.delegate?.window??.addSubview(self)
        }
我会在更新功能时  同步 感谢
