### ISSUE TITLE
请问可以自定义maximumWidth吗？

### ISSUE THREAD

**Issue by iOSyan** [Allen0828/AEAlertView#3]
如果，希望可以自定义AlertView距离屏幕左右两边的距离~

**Comment by Allen0828** [comment]
> 如果，希望可以自定义AlertView距离屏幕左右的距离~

目前版本不支持 在初始化是有默认值, 我会在下个版本添加. 
如果你现在需要 请修改源码
AEBaseAlertView->78行
`public var maximumWidth: CGFloat = 200`
200等于你想要的值

**Comment by iOSyan** [comment]
嗯嗯，直接修改源码是可以使用的，就是希望能提供给外部使用~期待下个版本，感谢！
